version: '3.4'

services:
  amourlink.recommendation:
    image: ${DOCKER_REGISTRY-}recommendation:latest
    build:
      context: ..
      dockerfile: AmourLink.Backend.CSharp/Services/AmourLink.Recommendation/Dockerfile
  
  amourlink.gateway:
    image: ${DOCKER_REGISTRY-}gateway:latest
    build:
      context: ..
      dockerfile: AmourLink.Backend.CSharp/Services/AmourLink.Gateway/Dockerfile
      
  amourlink.security:
    image: danyloz/amourlink-java-security-service:1.7
    
  amourlink.swipe:
    image: ${DOCKER_REGISTRY-}swipe:latest
    build:
      context: ..
      dockerfile: AmourLink.Backend.CSharp/Services/AmourLink.Swipe/Dockerfile
      
  amourlink.matching:
    image: ${DOCKER_REGISTRY-}matching:latest
    build:
      context: ..
      dockerfile: AmourLink.Backend.CSharp/Services/AmourLink.Matching/Dockerfile
    depends_on:
      - create-topics
    
  zookeeper:
    image: wurstmeister/zookeeper

  broker:
    image: wurstmeister/kafka
    hostname: broker
    depends_on:
      - zookeeper


  create-topics:
    image: wurstmeister/kafka
    depends_on:
      - broker
    entrypoint:
      - /bin/sh
      - -c
      - |
        # Wait for the Kafka broker to be ready
        echo "Waiting for Kafka broker to be ready..."
        while ! nc -z broker 3002; do   
          sleep 1
        done
        echo "Kafka broker is ready"
        
        # Create topics
        kafka-topics.sh --create --topic SwipeEvent --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181
        kafka-topics.sh --create --topic RatingEvent --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181

