version: '3.4'

services:
  amourlink.recommendation:
    image: ${DOCKER_REGISTRY-}recommendation:latest
    build:
      context: ..
      dockerfile: AmourLink.Backend.CSharp/API/AmourLink.Recommendation/Dockerfile
  
  amourlink.gateway:
    image: ${DOCKER_REGISTRY-}gateway:latest
    build:
      context: ..
      dockerfile: AmourLink.Backend.CSharp/AmourLink.Gateway/Dockerfile
      
  amourlink.security:
    image: danyloz/amourlink-java-security-service:1.5