version: '3.4'

services:
  amourlink.recommendation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnectionString=server=host.docker.internal;user=root;password=rootPassword;database=amourlink
    ports:
      - "8001:8080"
  
  amourlink.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8000:8080"
  
  amourlink.security:
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/amourlink
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootPassword
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8002:8081"